apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-golden-path-provisioner.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-golden-path-provisioner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8s-golden-path-provisioner.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-golden-path-provisioner.fullname" . }}
    spec:
      serviceAccountName: {{ include "k8s-golden-path-provisioner.fullname" . }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/manager"]
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          ports:
            - containerPort: 9443
              name: webhook-server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
