apiVersion: apps/v1
kind: Deployment
metadata:
  name: golden-path-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: golden-path
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: golden-path
  template:
    metadata:
      labels:
        app: golden-path
    spec:
      serviceAccountName: golden-path
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/manager"]
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          ports:
            - containerPort: 9443
              name: webhook-server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
